class MedicineModel {
  final int id; // Mã sản phẩm
  final String genericName; //Tên biệt dược
  final String activeIngredientName; // Tên hoạt chất
  final int priceIn1; // Giá mua thuốc ở dạng đóng gói thứ 1
  final int priceOut1; // Giá bán thuốc ở dạng đóng gói thứ 1
  final int priceOut2; //Giá bán thuốc ở dạng đóng gói thứ 2
  final int priceOut3; //Giá bán thuốc ở dạng đóng gói thứ 3
  final String volume1; // Dạng đóng gói thứ 1(hộp, lọ, chai...)
  final String
      volume2; //Dạng đóng gói thứ 2(vỉ, viên, lọ, chai, gói, tube,ống...)
  final String volume3; // Dạng đóng gói thứ 3(viên...)
  final String dosageForm; // Dạng dùng thuốc( viên, gói, ống, ml...)
  final int quanlity; // Số lượng thuốc trong kho

  const MedicineModel(
      {required this.id,
      required this.genericName,
      required this.activeIngredientName,
      required this.priceIn1,
      required this.priceOut1,
      required this.priceOut2,
      required this.priceOut3,
      required this.volume1,
      required this.volume2,
      required this.volume3,
      required this.dosageForm,
      required this.quanlity});

  static const List<MedicineModel> medicines = [
    MedicineModel(
        id: 1,
        genericName: "Paracetamol",
        activeIngredientName: "Acetaminophen",
        priceIn1: 50,
        priceOut1: 80,
        priceOut2: 150,
        priceOut3: 200,
        volume1: "Box",
        volume2: "Tablet",
        volume3: "Tablet",
        dosageForm: "Tablet",
        quanlity: 100),
    MedicineModel(
        id: 2,
        genericName: "Ibuprofen",
        activeIngredientName: "Ibuprofen",
        priceIn1: 80,
        priceOut1: 120,
        priceOut2: 200,
        priceOut3: 250,
        volume1: "Box",
        volume2: "Tablet",
        volume3: "Tablet",
        dosageForm: "Tablet",
        quanlity: 150),
    MedicineModel(
        id: 3,
        genericName: "Loratadine",
        activeIngredientName: "Loratadine",
        priceIn1: 60,
        priceOut1: 100,
        priceOut2: 180,
        priceOut3: 220,
        volume1: "Box",
        volume2: "Tablet",
        volume3: "Tablet",
        dosageForm: "Tablet",
        quanlity: 80),
    MedicineModel(
        id: 4,
        genericName: "Omeprazole",
        activeIngredientName: "Omeprazole",
        priceIn1: 120,
        priceOut1: 180,
        priceOut2: 300,
        priceOut3: 350,
        volume1: "Box",
        volume2: "Capsule",
        volume3: "Capsule",
        dosageForm: "Capsule",
        quanlity: 200),
    MedicineModel(
        id: 5,
        genericName: "Amoxicillin",
        activeIngredientName: "Amoxicillin",
        priceIn1: 100,
        priceOut1: 150,
        priceOut2: 250,
        priceOut3: 300,
        volume1: "Box",
        volume2: "Capsule",
        volume3: "Capsule",
        dosageForm: "Capsule",
        quanlity: 120),
    MedicineModel(
        id: 6,
        genericName: "Cetirizine",
        activeIngredientName: "Cetirizine",
        priceIn1: 70,
        priceOut1: 110,
        priceOut2: 200,
        priceOut3: 240,
        volume1: "Box",
        volume2: "Tablet",
        volume3: "Tablet",
        dosageForm: "Tablet",
        quanlity: 90),
    MedicineModel(
        id: 7,
        genericName: "Aspirin",
        activeIngredientName: "Acetylsalicylic Acid",
        priceIn1: 40,
        priceOut1: 70,
        priceOut2: 120,
        priceOut3: 150,
        volume1: "Box",
        volume2: "Tablet",
        volume3: "Tablet",
        dosageForm: "Tablet",
        quanlity: 150),
    MedicineModel(
        id: 8,
        genericName: "Ciprofloxacin",
        activeIngredientName: "Ciprofloxacin",
        priceIn1: 90,
        priceOut1: 140,
        priceOut2: 250,
        priceOut3: 300,
        volume1: "Box",
        volume2: "Tablet",
        volume3: "Tablet",
        dosageForm: "Tablet",
        quanlity: 100),
    MedicineModel(
        id: 9,
        genericName: "Simvastatin",
        activeIngredientName: "Simvastatin",
        priceIn1: 110,
        priceOut1: 160,
        priceOut2: 280,
        priceOut3: 330,
        volume1: "Box",
        volume2: "Tablet",
        volume3: "Tablet",
        dosageForm: "Tablet",
        quanlity: 80),
    MedicineModel(
        id: 10,
        genericName: "Metformin",
        activeIngredientName: "Metformin",
        priceIn1: 60,
        priceOut1: 100,
        priceOut2: 180,
        priceOut3: 220,
        volume1: "Box",
        volume2: "Tablet",
        volume3: "Tablet",
        dosageForm: "Tablet",
        quanlity: 120),
    MedicineModel(
        id: 11,
        genericName: "Atorvastatin",
        activeIngredientName: "Atorvastatin",
        priceIn1: 120,
        priceOut1: 180,
        priceOut2: 300,
        priceOut3: 350,
        volume1: "Box",
        volume2: "Tablet",
        volume3: "Tablet",
        dosageForm: "Tablet",
        quanlity: 200),
    MedicineModel(
        id: 12,
        genericName: "Azithromycin",
        activeIngredientName: "Azithromycin",
        priceIn1: 100,
        priceOut1: 150,
        priceOut2: 250,
        priceOut3: 300,
        volume1: "Box",
        volume2: "Capsule",
        volume3: "Capsule",
        dosageForm: "Capsule",
        quanlity: 120),
    MedicineModel(
        id: 13,
        genericName: "Furosemide",
        activeIngredientName: "Furosemide",
        priceIn1: 70,
        priceOut1: 110,
        priceOut2: 200,
        priceOut3: 240,
        volume1: "Box",
        volume2: "Tablet",
        volume3: "Tablet",
        dosageForm: "Tablet",
        quanlity: 90),
    MedicineModel(
        id: 14,
        genericName: "Prednisone",
        activeIngredientName: "Prednisone",
        priceIn1: 40,
        priceOut1: 70,
        priceOut2: 120,
        priceOut3: 150,
        volume1: "Box",
        volume2: "Tablet",
        volume3: "Tablet",
        dosageForm: "Tablet",
        quanlity: 150),
    MedicineModel(
        id: 15,
        genericName: "Metronidazole",
        activeIngredientName: "Metronidazole",
        priceIn1: 90,
        priceOut1: 140,
        priceOut2: 250,
        priceOut3: 300,
        volume1: "Box",
        volume2: "Tablet",
        volume3: "Tablet",
        dosageForm: "Tablet",
        quanlity: 100),
    MedicineModel(
        id: 16,
        genericName: "Amlodipine",
        activeIngredientName: "Amlodipine",
        priceIn1: 110,
        priceOut1: 160,
        priceOut2: 280,
        priceOut3: 330,
        volume1: "Box",
        volume2: "Tablet",
        volume3: "Tablet",
        dosageForm: "Tablet",
        quanlity: 80),
    MedicineModel(
        id: 17,
        genericName: "Levothyroxine",
        activeIngredientName: "Levothyroxine",
        priceIn1: 60,
        priceOut1: 100,
        priceOut2: 180,
        priceOut3: 220,
        volume1: "Box",
        volume2: "Tablet",
        volume3: "Tablet",
        dosageForm: "Tablet",
        quanlity: 120),
    MedicineModel(
        id: 18,
        genericName: "Losartan",
        activeIngredientName: "Losartan",
        priceIn1: 120,
        priceOut1: 180,
        priceOut2: 300,
        priceOut3: 350,
        volume1: "Box",
        volume2: "Tablet",
        volume3: "Tablet",
        dosageForm: "Tablet",
        quanlity: 200),
    MedicineModel(
        id: 19,
        genericName: "Warfarin",
        activeIngredientName: "Warfarin",
        priceIn1: 100,
        priceOut1: 150,
        priceOut2: 250,
        priceOut3: 300,
        volume1: "Box",
        volume2: "Capsule",
        volume3: "Capsule",
        dosageForm: "Capsule",
        quanlity: 120),
    MedicineModel(
        id: 20,
        genericName: "Metoprolol",
        activeIngredientName: "Metoprolol",
        priceIn1: 70,
        priceOut1: 110,
        priceOut2: 200,
        priceOut3: 240,
        volume1: "Box",
        volume2: "Tablet",
        volume3: "Tablet",
        dosageForm: "Tablet",
        quanlity: 90)
  ];
}
